theme: jekyll-theme-hacker
title: CAGE Challenge Info & Submissions
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
description: Copyright DST Group. Licensed under the MIT license.
